version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: testttt
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    target-branch: testtt
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    target-branch: 14-ksu
